[toolchain]
anchor_version = "0.31.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[workspace]
members = ["programs/cpi-sandbox"]

[programs.localnet]
cpi_sandbox = "4dcuyHs4K97LckqNVQEazKAwygJtAATLiuNWFsvFh11m"

[provider]
cluster = "localnet"
wallet = "tests/fixtures/keypairs/sandbox-local.json"
